# global:
#   scrape_interval: 10s
# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['localhost:9090']
#   - job_name: 'cadvisor'
#     static_configs:
#       - targets: ['cadvisor:8080']
#   - job_name: 'node-exporter'
#     static_configs:
#       - targets: ['node-exporter:9100']


############################################
# my global config
global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'mx-monitoring'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    scrape_interval: 10s
    static_configs: 
      - targets: ['cadvisor:8080','node-exporter:9100', 'nginx-exporter:9113']

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
